### ISSUE TITLE
Error: null is not an object (evaluating 'firstWord.offsetHeight')

### ISSUE THREAD

**Issue by ruieduardonunes** [NYTimes/text-balancer#7]
Hi! 
I'm using text-balancer with Gatsby and seeing the error above. 
Any idea how I could solve this? 
Thank you kindly!

**Comment by ColbyMay** [comment]
Why was this closed? 

I'm receiving `typeError: Cannot read properties of null (reading 'offsetHeight'` and I can't reliably duplicate it. Did you find the culprit?
